version: "3"

services:
  api:
    build:
      context: ./popuniv-spring
    ports:
      - 8080:8080
    command: ./gradlew bootRun
    environment:
      - ENV=development
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/qa?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpass
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
  web:
    build:
      context: ./popuniv-react
    ports: 
    - 3000:3000
    volumes:
      - ./popuniv-react:/usr/src/app
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis_test
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 5s
  mysql:
    container_name: mysql_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_DATABASE: qa
    command: # 명령어 실행
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib//mysql # mysql/data에 데이터를 담을 때 사용 합니다.
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #intidb.d의 create.sql을 실행
    healthcheck:
      test: mysql -h 127.0.0.1 -u root --password=rootpass qa -e 'SHOW TABLES'