spring:
  application:
    name: popuniv-spring-kotlin
  datasource:
    url: jdbc:mysql://localhost:3306/popuniv?serverTimezone=UTC
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  error:
    include-message: always