spring:
  application:
    name: popuniv-spring-kotlin
  datasource:
    url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  paths-to-match: /**
  swagger-ui:
    path: /swagger
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true
server:
  error:
    include-message: always